spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.url=jdbc:postgresql://localhost:5432/pp_event_website
spring.datasource.username=postgres
spring.datasource.password=123987
spring.datasource.driver-class-name=org.postgresql.Driver